name: timezone_country
description: >-
  Convert IANA timezones to ISO 3166-1 country codes and back.
  Country names, flag emoji, alpha-2/alpha-3 support.
  Pure Dart, zero dependencies, O(1) const-map lookups.
version: 1.0.1
homepage: https://github.com/DenisNikonov/timezone_country
repository: https://github.com/DenisNikonov/timezone_country
issue_tracker: https://github.com/DenisNikonov/timezone_country/issues
topics:
  - timezone
  - country-code
  - iso-3166
  - flag-emoji
  - i18n

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ^3.7.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.0
